//TABS
export const SELECT_TAB = 'SELECT_TAB';

//CHANNELS
export const POLL_CHANNELS = 'POLL_CHANNELS';
export const PUT_CHANNELS_SUCCEED = 'PUT_CHANNELS_SUCCEED';
export const PUT_CHANNELS_FAILED = 'PUT_CHANNELS_FAILED';
export const CLOSE_CHANNELS_SUCCEED = 'CLOSE_CHANNELS_SUCCEED';
export const DEPOSIT_CHANNELS_SUCCEED = 'DEPOSIT_CHANNELS_SUCCEED';

//TOKENS
export const POLL_TOKENS = 'POLL_TOKENS';
export const LEAVE_SUCCEED = 'LEAVE_SUCCEED';
export const JOIN_SUCCEED = 'JOIN_SUCCEED';

//PAYMENTS
export const GET_PAYMENTS = 'GET_PAYMENTS';
export const POLL_PAYMENTS = 'POLL_PAYMENTS';
export const  PAYMENT_SUCCEED = 'PAYMENT_SUCCEED';

//DASHBOARD
export const DASHBOAR_DATA_SUCCEED = 'DASHBOAR_DATA_SUCCEED';

//SEARCH
export const UPDATE_INPUT_VALUE = 'UPDATE_INPUT_VALUE';
export const CLEAR_SUGGESTIONS = 'CLEAR_SUGGESTIONS';
export const LOAD_SUGGESTIONS_BEGIN = 'LOAD_SUGGESTIONS_BEGIN';
export const MAYBE_UPDATE_SUGGESTIONS = 'MAYBE_UPDATE_SUGGESTIONS';
export const NO_SUGGESTIONS = 'NO_SUGGESTIONS';
export const SUGGESTION = 'SUGGESTION';

//TASKS
export const TASK_PENDING = 'TASK_PENDING';
export const TASK_COMPLETE = 'TASK_COMPLETE';
export const TASK_FAILED = 'TASK_FAILED';

